version: '3'
services:
  server:
    container_name: server
    build:
      dockerfile: Dockerfile.env
      context: ./server
    ports:
      - 4000:4000
    networks:
      - backend
    environment:
      - APP_NAME=docs-backend
      - APP_HOST=127.0.0.1
      - APP_PORT=4000
      - LOG_ENABLED=true
      - LOG_LEVEL=all
      - DB_URI=mongodb://mongo:27017/admin
      - DB_USER=docs
      - DB_PASS=1205360
    volumes:  
      - "/var/jenkins_home/app/aws:/app/app/aws"
  client:
    container_name: client
    build:
      dockerfile: Dockerfile.env
      context: ./client
    ports:
      - 80:80
    networks:
      - backend
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docs
      - MONGO_INITDB_ROOT_PASSWORD=1205360
    volumes:
      - "$HOME/data/db:/data/db"

networks:
  backend:
    driver: bridge