FROM node:12-slim

RUN npm install -g yarn

WORKDIR /app

COPY ./package.json .

RUN yarn install

COPY . .

RUN touch /app/app/configs/awsconfig.json
VOLUME /app/app/configs/awsconfig.json

EXPOSE 4000

CMD [ "yarn", "start" ]